name: cliente_facil
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # https://flutter.dev/to/resolution-aware-images


  fonts:
    - family: TitanOne
      fonts:
         - asset: assets/fonts/TitanOne-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
